### ISSUE TITLE
[bug] Option metrics.serviceMonitor.release is ignored

### ISSUE THREAD

**Issue by dmdb** [centrifugal/helm-charts#26]
Is chart ignores `metrics.serviceMonitor.release` option?

values.yaml:
```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "kube-prometheus-stack"
    release: "kube-prometheus-stack"
```

`helm install centrifugo -f values.yaml centrifugal/centrifugo --debug --dry-run > test.yaml`

test.yaml:
```apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: centrifugo
  namespace: kube-prometheus-stack
  labels:
    helm.sh/chart: centrifugo-7.2.1
    app.kubernetes.io/name: centrifugo
    app.kubernetes.io/instance: centrifugo
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - port: internal
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: centrifugo
      app.kubernetes.io/instance: centrifugo
  namespaceSelector:
    matchNames:
      - default
```

Sorry if that is misunderstanding of docs, but I was expecting it here:

```
metadata:
  name: centrifugo
  namespace: kube-prometheus-stack
  labels:
    helm.sh/chart: centrifugo-7.2.1
    app.kubernetes.io/name: centrifugo
    app.kubernetes.io/instance: centrifugo
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/managed-by: Helm
    release: "kube-prometheus-stack"
```
Works as `metrics.serviceMonitor.additionalLabels`
