### ISSUE TITLE
How to configure TLS? 

### ISSUE THREAD

**Issue by berayb** [centrifugal/helm-charts#28]
Hi, it is not clear from the documentation how to configure TLS with helm deployment. Is there any example that you can provide? 

Thanks,

**Comment by FZambia** [comment]
For minikube with self-signed cert.

Add minikube ip to `etc/hosts`, in my case:

```
192.168.64.2    centrifugo.com
```

Create cert:
```
openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout tls.key -out tls.crt -subj "/CN=centrifugo.com" -days 365
```

Create secret:

```
kubectl create secret tls centrifugo-tls --cert=tls.crt --key=tls.key
```

`myvalues.yaml`:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: centrifugo.com
      paths:
        - /
  tls:
    - secretName: centrifugo-tls
      hosts:
        - centrifugo.com
```

Install into minikube:

```
minikube addons enable ingress
helm install centrifugo -f myvalues.yaml ./centrifugo
```

Then:
```
wscat --connect wss://centrifugo.com/connection/websocket --ca tls.crt
Connected (press CTRL+C to quit)
```

**Comment by berayb** [comment]
So, I want to share the entire config to see what we are missing here. 

## Using Letsencrypt and Certbot

 ```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wss
spec:
  acme:
    # The ACME server URL 
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: infra@test.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-wss
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
```

          
 ## Ingress YAML
 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wss-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-wss"
spec:
  rules:
  - host: test.test.com
    http:
      paths:
      - backend:
          serviceName: centrifugo-wss
          servicePort: 9000

  tls:
  - hosts:
    - test.test.com
    secretName: letsencrypt-wss
    
 ```

## Service YAML
```
apiVersion: v1
kind: Service
metadata:
  name: centrifugo-wss
  labels:
    app: centrifugo-wss
    group: testing
spec:
  type: ClusterIP
  ports:
    - name: wss
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: portal
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: centrifugo
```

## Ingress-nginx

  
 ```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    
    ```

    
 
Ingress disabled from Centrifugo helm values config
